
spring:
  application:
    name: consumer
  cloud:
    stream:
      function:
        definition: processRiderLocation
      bindings:
          processRiderLocation-in-0:
            destination: my-topic-new
    kafka:
      binder:
        broker: localhost:9092



#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.demo.consumer.RiderLocation

server:
  port: 8081
